version: '2.4'
services:
  redis:
    image: redis:5.0.6
    container_name: redis
    restart: always
    read_only: true
    mem_limit: ${REDISMEMLIMIT}
    cpus: ${REDISCPUS}
    cpu_shares: 128
    pids_limit: 15
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc:
        soft: 16
        hard: 32
    cap_drop:
      - MKNOD
      - SYS_CHROOT
    volumes:
      - "redis_data:/data:rw"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  mail:
    image: postfix:1.0
    restart: always
    container_name: mail
    read_only: false
    mem_limit: ${MAILMEMLIMIT}
    cpu_shares: 128
    cpus: ${MAILCPUS}
    pids_limit: 30
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc: 
        soft: 16
        hard: 32
    build:
      context: ./
      dockerfile: postfix/Dockerfile
    cap_drop:
      - MKNOD
      - SYS_CHROOT
    tmpfs:
      - /tmp
      - /var/tmp
      - /usr/tmp
      - /run
      - /var/run
    volumes:
      - "./postfix_data/main.cf:/etc/postfix/main.cf:rw"
      - "postfix_etc:/etc:rw"
      - "postfix_var_log:/var/log:rw"
      - "postfix_var_mail:/var/mail:rw"
      - "postfix_var_spool:/var/spool:rw"
      - "postfix_opt:/opt:rw"
      - "postfix_var_lib:/var/lib:rw"
    ports:
      - "127.0.0.1:25:25"
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "25"]
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    read_only: true
    mem_limit: ${MYSQLMEMLIMIT}
    cpu_shares: 512
    cpus: ${MYSQLCPUS}
    pids_limit: 70
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc:
        soft: 256
        hard: 512
    environment:
      - "MYSQL_USER=${MYSQLUSER}"
      - "MYSQL_PASSWORD=${MYSQLPASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDATABASE}"
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
      - /var/run
      - /var/run/mysqld
    volumes:
      - "mysql_var_lib:/var/lib:rw"
      - "mysql_var_log:/var/log:rw"
      - "mysql_var_lib_mysql:/var/lib/mysql:rw"
      - "mysql_etc:/etc:rw"
    cap_add:
      - SYS_NICE
    cap_drop:
      - MKNOD
      - SYS_CHROOT
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppassword", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    restart: always
    read_only: true
    mem_limit: ${MISPMODMEMLIMIT}
    cpu_shares: 128
    cpus: ${MISPMODCPUS}
    container_name: misp-modules
    pids_limit: 5
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc:
        soft: 16
        hard: 32
    build:
      context: ./
      dockerfile: misp-modules-Dockerfile
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db
    cap_drop:
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - SETFCAP
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "6666"]
      timeout: 10s
      retries: 5

  misp:
    image: coolacid/misp-docker:core-latest
    restart: always
    container_name: misp-web
    read_only: false
    mem_limit: ${MISPMEMLIMIT}
    cpu_shares: 512
    cpus: ${MISPCPUS}
    pids_limit: 70
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc:
        soft: 256
        hard: 512
    build:
      context: ./
      dockerfile: misp-Dockerfile
    depends_on:
      - redis
      - db
    ports:
      - "${SERVER_NAME}:80:80"
      - "${SERVER_NAME}:443:443"
    tmpfs:
      - /tmp
      - /var/tmp
      - /usr/tmp
      - /run
      - /var/run
      - /var/run/php
    volumes:
      - "./server-configs/:/var/www/MISP/app/Config/:rw"
      - "./logs/:/var/www/MISP/app/tmp/logs/:rw"
      - "./files/:/var/www/MISP/app/files:rw"
      - "./ssl/:/etc/nginx/certs:rw"
      - "./nginx/misp80:/etc/nginx/sites-available/misp80"
      - "./nginx/misp:/etc/nginx/sites-available/misp"
      - "misp_var_www_misp:/var/www"
      - "misp_var_log:/var/log:rw"
      - "misp_var_lib:/var/lib:rw"
      - "misp_etc:/etc:rw"
    environment:
      - "HOSTNAME=https://${SERVER_NAME}"
      - "REDIS_FQDN=redis"
      - "INIT=true"
      - "CRON_USER_ID=1"
    cap_drop:
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - SETFCAP
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "443"]
      timeout: 10s
      retries: 5


volumes:
  redis_data:

  postfix_var_log:
  postfix_var_mail:
  postfix_var_spool:
  postfix_var_lib:
  postfix_opt:
  postfix_etc:

  mysql_var_lib_mysql:
  mysql_var_lib:
  mysql_var_log:
  mysql_etc:

  misp_var_log:
  misp_var_lib:
  misp_var_www_misp:
  misp_etc:

