version: '2.4'
services:
  redis:
    image: redis:5.0.6
    container_name: redis
    restart: always
    read_only: false
    mem_limit: 50M
    cpus: 0.5
    cpu_shares: 128
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  mail:
    image: catatnight/postfix
    restart: always
    container_name: mail
    read_only: false
    build:
      context: ./
      dockerfile: mail-Dockerfile
    volumes:
      - "./postfix/main.cf:/etc/postfix/main.cf"
    ports:
      - "127.0.0.1:25:25"
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "25"]
      timeout: 10s
      retries: 5


