version: '2.4'
services:
  db:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    read_only: true
    mem_limit: 2048M
    cpu_shares: 512
    environment:
      - "MYSQL_USER=${MYSQLUSER}"
      - "MYSQL_PASSWORD=${MYSQLPASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDATABASE}"
    volumes:
      - "mysql_var_lib:/var/lib:rw"
      - "mysql_var_run:/var/run:rw"
      - "mysql_run:/run:rw"
      - "mysql_var_log:/var/log:rw"
      - "mysql_etc:/etc:rw"
      - "mysql_tmp:/tmp:rw"
      - "mysql_var_tmp:/var/tmp:rw"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppassword", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
    mysql_var_lib:
    mysql_var_run:
    mysql_run:
    mysql_var_log:
    mysql_etc:
    mysql_tmp:
    mysql_var_tmp:

